<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class EcommerceSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();

        // 1. Users
        $db->table('users')->truncate();
        $db->table('users')->insertBatch([
            [
                'name'       => 'Kagzi Admin',
                'email'      => 'admin@kagziventures.in',
                'password'   => password_hash('admin123', PASSWORD_DEFAULT),
                'phone'      => '+123 456 7890',
                'address'    => '123 Enterprise Way, Business Park',
                'role'       => 'admin',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name'       => 'John Doe',
                'email'      => 'customer@example.com',
                'password'   => password_hash('customer123', PASSWORD_DEFAULT),
                'phone'      => '+987 654 3210',
                'address'    => '456 Main Street, Cityville',
                'role'       => 'customer',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);

        // 2. Categories
        $db->table('categories')->truncate();
        $db->table('categories')->insertBatch([
            [
                'id'          => 1,
                'name'        => 'Fashion',
                'slug'        => 'fashion',
                'description' => 'Trendy apparel, jackets, and outfits for all seasons.',
                'image'       => 'assets/images/demoes/demo1/cats/cat-1.jpg',
                'parent_id'   => 0,
                'status'      => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'id'          => 2,
                'name'        => 'Electronics',
                'slug'        => 'electronics',
                'description' => 'Latest smart gadgets, audio, and accessories.',
                'image'       => 'assets/images/demoes/demo1/cats/cat-2.jpg',
                'parent_id'   => 0,
                'status'      => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'id'          => 3,
                'name'        => 'Home & Garden',
                'slug'        => 'home-garden',
                'description' => 'Premium home decor, lighting, and living essentials.',
                'image'       => 'assets/images/demoes/demo1/cats/cat-3.jpg',
                'parent_id'   => 0,
                'status'      => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'id'          => 4,
                'name'        => 'Accessories',
                'slug'        => 'accessories',
                'description' => 'Bags, belts, sunglasses, and stylish add-ons.',
                'image'       => 'assets/images/demoes/demo1/cats/cat-4.jpg',
                'parent_id'   => 0,
                'status'      => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'id'          => 5,
                'name'        => 'Shoes',
                'slug'        => 'shoes',
                'description' => 'Comfortable sneakers, formal shoes, and boots.',
                'image'       => 'assets/images/demoes/demo1/cats/cat-5.jpg',
                'parent_id'   => 0,
                'status'      => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
        ]);

        // 3. Products
        $db->table('products')->truncate();
        $db->table('products')->insertBatch([
            [
                'name'              => 'Wireless Over-Ear Headphones',
                'slug'              => 'wireless-over-ear-headphones',
                'category_id'       => 2,
                'sku'               => 'HD-WIR-001',
                'price'             => 199.00,
                'sale_price'        => 149.00,
                'stock_quantity'    => 50,
                'short_description' => 'High fidelity wireless bluetooth headset with deep bass surround sound.',
                'features'          => "• Active Noise Cancellation (ANC) up to 35dB\n• 40-Hour Battery Life with Quick Charge (10 min charge = 4 hrs)\n• Soft Memory Foam Earcups for All-day Ergonomic Comfort\n• Bluetooth 5.2 Low Latency Wireless Connectivity\n• Built-in Dual HD Microphones for Crystal Clear Calls",
                'specifications'    => "Brand: Kagzi Audio\nDriver Size: 40mm Neodymium\nFrequency Response: 20Hz - 20kHz\nBluetooth Range: 15 Meters\nWarranty: 1 Year Manufacturer Warranty",
                'description'       => 'Experience crystal clear high audio precision with 360-degree surround sound technology, active noise cancellation rating, and 40-hour battery life.',
                'main_image'        => 'assets/images/demoes/demo1/products/product-1.jpg',
                'images'            => json_encode(['assets/images/demoes/demo1/products/product-1-2.jpg']),
                'featured'          => 1,
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Portable Battery Charger',
                'slug'              => 'portable-battery-charger',
                'category_id'       => 2,
                'sku'               => 'CHG-BAT-002',
                'price'             => 49.00,
                'sale_price'        => 29.00,
                'stock_quantity'    => 35,
                'short_description' => 'Fast charging power bank compatible with all smart devices.',
                'features'          => "• 20,000mAh Ultra High Capacity Battery Pack\n• 22.5W Fast Charge PD 3.0 & QuickCharge Technology\n• Dual USB-A + Type-C Output/Input Ports\n• Intelligent LED Digital Battery Level Indicator\n• Overcharge, Short Circuit & Thermal Protection",
                'specifications'    => "Brand: Kagzi Power\nCapacity: 20,000mAh 3.7V (74Wh)\nInput: Type-C 5V/3A, 9V/2A\nOutput: 5V/4.5A, 9V/2.25A Max\nWeight: 340g",
                'description'       => 'High capacity 20,000mAh portable charger with dual USB fast-charge ports and intelligent safety cut-off protection.',
                'main_image'        => 'assets/images/demoes/demo1/products/product-2.jpg',
                'images'            => json_encode(['assets/images/demoes/demo1/products/product-2.jpg']),
                'featured'          => 1,
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Brown Women Casual Handbag',
                'slug'              => 'brown-women-casual-handbag',
                'category_id'       => 4,
                'sku'               => 'BAG-BRN-003',
                'price'             => 129.00,
                'sale_price'        => 89.00,
                'stock_quantity'    => 40,
                'short_description' => 'Premium genuine leather handbag for daily travel and elegance.',
                'features'          => "• 100% Genuine Grain Italian Leather Finish\n• Reinforced Stitching & Antique Gold Brass Hardware\n• Spacious Zippered Main Compartment + Internal Pockets\n• Detachable & Adjustable Leather Shoulder Strap\n• Protective Metal Feet Base Studs",
                'specifications'    => "Material: Genuine Grain Leather\nDimensions: 32cm x 24cm x 14cm\nClosure: Heavy Duty YKK Zipper\nColor: Dark Saddle Brown",
                'description'       => 'Crafted with top-grain leather, spacious compartments, durable brass zippers, and detachable shoulder strap.',
                'main_image'        => 'assets/images/demoes/demo1/products/product-3.jpg',
                'images'            => json_encode(['assets/images/demoes/demo1/products/product-3-2.jpg']),
                'featured'          => 1,
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Casual Travel Note Bag',
                'slug'              => 'casual-travel-note-bag',
                'category_id'       => 4,
                'sku'               => 'BAG-NTE-004',
                'price'             => 79.00,
                'sale_price'        => 59.00,
                'stock_quantity'    => 60,
                'short_description' => 'Waterproof lightweight shoulder notebook bag with padded laptop sleeve.',
                'features'          => "• High-Density 900D Water-Repellent Nylon Construction\n• Padded Shockproof Compartment Fits up to 15.6 Inch Laptops\n• Hidden Rear Anti-Theft Zipper Pocket\n• Ergonomic Air-Mesh Shoulder Strap Padding\n• Integrated USB Charging Pass-Through Port",
                'specifications'    => "Laptop Fit: Up to 15.6 Inch\nVolume Capacity: 22 Liters\nWater Resistance: Splash Proof Hydro-Shield",
                'description'       => 'Sleek modern design engineered with water-resistant fabric and multiple organizer pockets.',
                'main_image'        => 'assets/images/demoes/demo1/products/product-4.jpg',
                'images'            => json_encode(['assets/images/demoes/demo1/products/product-4-2.jpg']),
                'featured'          => 1,
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Porto Extended HD Camera',
                'slug'              => 'porto-extended-hd-camera',
                'category_id'       => 2,
                'sku'               => 'CAM-EXT-005',
                'price'             => 399.00,
                'sale_price'        => 299.00,
                'stock_quantity'    => 25,
                'short_description' => 'Professional 4K Ultra HD digital camera with optical zoom lens.',
                'features'          => "• 4K 60FPS Ultra HD Video & 48MP Still Photos\n• 16X Digital Optical Zoom with Optical Image Stabilization (OIS)\n• 3.0 Inch 180-Degree Flip Touchscreen LCD\n• Built-in Wi-Fi & Live Streaming Webcam Functionality\n• Dual Battery Pack Included in Retail Box",
                'specifications'    => "Sensor Type: CMOS 24.2MP Sensor\nVideo Resolution: 4K 3840x2160\nLens Aperture: F/2.0 f=7.36mm",
                'description'       => 'Capture stunning high-resolution video and photos with advanced autofocus, night vision, and Wi-Fi streaming.',
                'main_image'        => 'assets/images/demoes/demo1/products/product-5.jpg',
                'images'            => json_encode(['assets/images/demoes/demo1/products/product-5-2.jpg']),
                'featured'          => 1,
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Casual Women Winter Jacket',
                'slug'              => 'casual-women-winter-jacket',
                'category_id'       => 1,
                'sku'               => 'JKT-WM-006',
                'price'             => 159.00,
                'sale_price'        => 119.00,
                'stock_quantity'    => 45,
                'short_description' => 'Insulated lightweight hooded jacket designed for warmth and style.',
                'features'          => "• Windproof Thermal Insulation Layer\n• Detachable Fleece Lined Hood with Drawstrings\n• Zippered Hand Pockets + Internal Security Pocket\n• Machine Washable Premium Durable Polyester Fabric",
                'specifications'    => "Outer Fabric: 100% Wind-Shield Polyester\nLining: Thermal Fleece Blend\nCare: Machine Wash Cold",
                'description'       => 'Features windproof outer shell, cozy interior lining, zippered pockets, and tailored fit.',
                'main_image'        => 'assets/images/products/product-1.jpg',
                'images'            => json_encode(['assets/images/products/product-1-2.jpg']),
                'featured'          => 1,
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Modern Living Room Decor Lamp',
                'slug'              => 'modern-living-room-decor-lamp',
                'category_id'       => 3,
                'sku'               => 'LMP-MOD-007',
                'price'             => 85.00,
                'sale_price'        => null,
                'stock_quantity'    => 30,
                'short_description' => 'Adjustable touch control LED desk lamp with wireless phone charger base.',
                'features'          => "• 10W Fast Qi Wireless Charging Base Pad\n• 5 Color Temperatures (2700K - 6500K) + 5 Brightness Levels\n• Touch Control Panel with 45-Minute Auto-Off Timer\n• Flexible Gooseneck Arm with 360-Degree Rotation",
                'specifications'    => "Light Source: LED 12W (800 Lumens)\nInput Voltage: DC 12V/2A\nBulb Life: 50,000 Hours",
                'description'       => 'Features 5 brightness levels, 3 color temperatures, and energy-saving eye protection LED bulbs.',
                'main_image'        => 'assets/images/products/product-17.jpg',
                'images'            => json_encode(['assets/images/products/product-17.jpg']),
                'featured'          => 1,
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Brown Casual Leather Shoes',
                'slug'              => 'brown-casual-leather-shoes',
                'category_id'       => 5,
                'sku'               => 'SH-BRN-008',
                'price'             => 89.00,
                'sale_price'        => 69.00,
                'stock_quantity'    => 20,
                'short_description' => 'Handcrafted genuine leather shoes for smart casual wear.',
                'features'          => "• Hand-Burnished Full Grain Genuine Cowhide Leather\n• Ergonomic Cushioned Memory Foam Insole\n• Anti-Slip Flexible Rubber Grip Outsole\n• Breathable Moisture-Wicking Leather Lining",
                'specifications'    => "Upper: Full Grain Cowhide Leather\nOutsole: Vulcanized Non-Slip Rubber\nSole Construction: Goodyear Welted",
                'description'       => 'Constructed with premium full-grain leather, cushioned insoles for all-day comfort, and non-slip rubber outsoles.',
                'main_image'        => 'assets/images/products/product-2.jpg',
                'images'            => json_encode(['assets/images/products/product-2.jpg']),
                'featured'          => 1,
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
